<div class="page-header">
	<h1 class="page-title">Często zadawane pytania (FAQ)</h1>
	<a href="<?php echo $this->url(array('controller'=>'index','action'=>'index'));?>">
		<img src="img/main_logo.png" alt="ekopal_logo" class="logo-small" />
	</a>	
</div>
<div id="accordion">
	<h2>Jakie jest zuzycie paliwa w produkowanych przez was piecach?</h2>
	<p>
		Na  ilość spalanego paliwa składa się wiele czynników takich jak: kubatura jaką trzeba ogrzać, temperatura na zewnątrz budynku, temperatura jaką chcemy utrzymywać w mieszkaniu, sposób izolacji budynku, szczelność okien, wentylacja, itp. <br /><br />Z doświadczeń klientów naszej firmy możemy przyjąć, że do ogrzania domu o powierzchni 200m­2 wykonany w technologii murowanej, bez ocieplenia potrzeba około 8 ton zrębki mieszanej (iglasto-liściastej) o wilgotności około 20% na cały sezon grzewczy, co przy cenie 350zł/tonę daje kwotę 2800zł.
	</p>
	<h2>Na jak długo wystarcza zasyp zbiornika?</h2>
	<p>
		Szybkość spalania paliwa jest ściśle powiązana z poborem energii i jego jakością.  Z doświadczeń klientów naszej firmy możemy przyjąć, że przy ogrzewaniu domu o powierzchni 200m­2 wykonanym w technologii murowanej, bez ocieplenia, piecem ECONOMIC-BIO 25 pełen zbiornik paliwa wystarcza na  około 24h przy średniej temperaturze w sezonie grzewczym.
	</p>
	<h2>Jaką powierzchnię można ogrzać daną wielkością kotła?</h2>
	<p>
		Nasz firma produkuje trzy wielkości kotłów. 25kW, 38kW, 50kW. Dla domów jednorodzinnych do 280m2 na ogół wystarcza kocioł 25kW. Kocioł 50kW jest w stanie ogrzać powierzchnię około 500m2 powierzchni.
	</p>
	<h2>
		Czy udzielacie gwarancji na kotły?
	</h2>
	<p>Tak. Cały zestaw (kocioł, podajnik, palnik) jest objęty 48 miesięczną gwarancją.</p>
	<h2>Gdzie można zakupić wasze kotły?</h2>

	<p>Kotły naszej produkcji są sprzedawane wyłącznie w naszej firmie.</p>

	<h2>W jaki sposób można zamówić wasze kotły i ile trzeba czekać na realizację zamówienia?</h2>
	<p>
		Kotły naszej produkcji można zamawiać poprzez adres e-mail: stefan@manka.info podając następujące informacje:<br /><br />
		Dla osoby prywatnej:<br />
		Imię:<br />
		Nazwisko:<br />
		PESEL:<br />
		Nr. Telefonu:<br />
		Moc kotła:<br />
		Sposób ustawienia kotła względem podajnika (prawy lub lewy):<br /><br />
		Dla działalności gospodarczej:<br />
		Nazwa firmy:<br />
		Nip:<br />
		Nr. Telefonu:<br />
		Moc kotła:<br />
		Sposób ustawienia kotła względem podajnika (prawy lub lewy):<br />
		Czas realizacji zamówienia wynosi do 6 tygodni od momentu wpłacenia zaliczki.</p>
	<h2>Czy w cenie zawarty jest koszt transportu?</h2>
	<p>
	Nie, jednakże po uzgodnieniu kosztów transportu możemy dostarczyć kocioł do klienta.</p>
	<h2>Gdzie można zobaczyć wasze kotły w trakcje eksploatacji?</h2>
	<p>
	Przykładowa instalacja znajduje się w siedzibie naszej firmy. Za zgodą naszych klientów możemy udostępnić również adresy instalacji w Państwa okolicy. Ich lokalizacje można znaleść na naszej <a href="<?php echo $this->url(array('module'=>'default', 'controller'=>'client-map', 'action'=>'index')); ?>"><b>mapie</b></a>.</p>
	<h2>Jaka musi być frakcja paliwa?</h2>
	<p>
	Urządzenie najlepiej pracuje jeżeli frakcja paliwa nie przekracza średnicy 5cm. Jeżeli zdarzą się elementy do 7cm, nie wpłyną one na działanie podajnika.</p>
	<h2>Jaka musi być wilgotność paliwa</h2>
	<p>
	Czym paliwo jest suchsze tym jest wydajniejsze. Ważne jest, żeby paliwo nie przekraczało 25% wilgotności.</p>
	<h2>Czy można spalać trociny</h2>
	<p>Urządzenie nie jest przeznaczone do samodzielnego spalania trocin. Można w niewielkiej proporcji mieszać trociny ze zrębami.</p>
	<h2>Czy można spalać węgiel kamienny</h2>
	<p>Nie. Nasze urządzenia są zaprojektowane do spalania wyłącznie biomasy.</p>
	<h2>Czy można awaryjnie spalać drewno kominkowe</h2>
	<p>
	Do kotła można założyć awaryjnie ruszt na którym można spalać drewno kominkowe, jednakże jest to ekonomicznie nieuzasadnione.</p>
	<h2>Jakie są zabezpieczenia przed cofaniem się ognia</h2> 
	<p>
		Nasze urządzenia są kilkakrotnie zabezpieczone przez cofaniem się ognia do tunelu podającego:
		Elektronicznie: jeżeli wzrośnie temperatura podajnika do zaprogramowanej w sterowniku to sterownik włączy podajnik i wypchnie palące się paliwo do palnika do momentu wyłączenia podajnika przez wyłącznik krańcowy.
		Mechaniczne: klapa w palniku oraz klapa w podajniku oddzielają ogień od zbiornika z paliwem.
		Mechaniczne: urządzenia podające kończą cykl podawania rozsuwając paliwo od zbiornika.
		Wodne: tzw.: strażak, urządzenie działa niezależnie od zasilania energią elektryczną. W momencie nagrzania kanału podajnika do temperatury 95 stopni czujnik otwiera zawór przez który woda dostaje się za pomocą zraszaczy do kanału podajnika obniżając temperaturą w kanale.</p>
	<h2>Czy można podgrzewać wodę przez cały rok</h2>
	<p>Tak, sterownik posiada funkcję „tryb letni”, w tym trybie pracuje tylko pompa CWU. </p>
	<h2>Czy jest konieczny montaż zaworu trójdrożnego</h2>
	<p>Do pracy naszego urządzenia nie jest potrzebny montaż takiego urządzenia. </p>
	<h2>Czy wymagany jest zbiornik akumulacyjny</h2>
	<p>Nie.</p>
	<h2>Z jakiej blachy wykonany jest kocioł</h2>
	<p>Nasze kotły wykonane są z blachy kotłowej atestowanej gr. 6mm.</p>
	<h2>Czy można założyć awaryjny ruszt</h2>
	<p>Kocioł jest przystosowany do założenia awaryjnego rusztu.</p>
	<h2>Jak zachowuje się urządzenie w przypadku  przerwy w dostawie energii elektrycznej</h2>
	<p>
		Urządzenie jest zaprojektowane w ten sposób, że w momencie przerwy w dostawie energii elektrycznej nieznacznie podnosi temperaturę wody w kotle. W momencie wznowienia dostawy prądu, kocioł automatycznie powraca do stanu poprzedniego. Brak dopływu energii elektrycznej w czasie około 1 godziny nie powinien spowodować wygaszenia kotła. 
	</p>


</div>	


<?php 
	$this->headScript()->appendFile('js/accordion.js')
						->appendFile('js/jquery-ui.js');
	$this->headLink()->appendStylesheet('css/accordion.css');
?>
