

	<a href="<?php echo $this->url(array('controller'=>'index','action'=>'index'));?>">
		<img src="img/main_logo.png" alt="ekopal_logo" class="logo" />			
	</a>
		<div style="clear:both; text-align:center;">
			<span class="h2">ciepły dom w zgodzie z naturą</span>
		</div>
		
		<div style="height:20px;"></div>

		<div id="index-page-wrapper">
			<div id="index-page-left-collumn">
				<p>
					<b>Czy wiesz, że? </b>
				</p>
				<p>
					 Paliwo ekologiczne jest powszechnie dostępne. Żeby ogrzewać nim dom, nie trzeba pozyskiwać go we własnym zakresie. Można go kupić na podobnych zasadach jak na przykład węgiel czy olej opałowy.
				</p>
			</div>			
			<div id="furnace-flah">
				<OBJECT classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,0,0" WIDTH="320" HEIGHT="240" id="flash/Piec ekopal.swf" ALIGN="">
			 		<PARAM NAME=movie VALUE="flash/Piec ekopal.swf"> 
			 		<PARAM NAME=quality VALUE=high> 
			 		<PARAM NAME=bgcolor VALUE=#333399> 
			 		<EMBED src="flash/Piec ekopal.swf" quality=high bgcolor=#333399 WIDTH="320" HEIGHT="240" NAME="flash/Piec ekopal.swf" ALIGN="" TYPE="application/x-shockwave-flash" PLUGINSPAGE="http://www.macromedia.com/go/getflashplayer"></EMBED> 
	 			</OBJECT>
			</div>
                        <div style="height:50px; clear:both;"></div>
                        <div id="youtube-video">
                            <iframe width="480" height="360" src="http://www.youtube.com/embed/0sHTSqALyJ8" frameborder="0" allowfullscreen></iframe>
                        </div>
                        <div id="index-page-text-rght">
				<p>
					 Filmik opisujący produkowane przez nas piece oraz niektóre rodzaje surowców, które mogą być wykorzystywane w nich jako paliwo.
				</p>
			</div>	
                </div>
