<div class="page-header">

	<h1 class="page-title" >Zasada działania naszych kotłów</h1>
	<a href="<?php echo $this->url(array('controller'=>'index','action'=>'index'));?>">
		<img src="img/main_logo.png" alt="ekopal_logo" class="logo-small" />
	</a>
	
</div>
<hr />
<div class="container">

<h2>Zestaw grzewczy składa się z trzech podstawowych części</h2>
 
<ul class="list">
	<li>
		Kocioł – wymiennik ciepła w którym ciepło z palących się zrębków wymienia się na ciepło w centralnym ogrzewaniu domu.
	</li>
	<li>
		Palnik – urządzenie w którym zrębki palą się w dwóch fazach. Najpierw w wysokiej temperaturze palnika wytwarza się gaz drzewny który pali się od razu mieszając się w odpowiedniej proporcji z powietrzem. W drugiej fazie zrębki drewniane, które po zgazowaniu zamieniają się w węgiel drzewny dopalają się, a w dalszej części palnika pozostałością ze spalonych zrębków jest znikomej ilości popiół, który jako, że jest z paliwa ekologicznego (drewna) może być wykorzystany jako nawóz.
	</li>
	<li>
		Zasobnik z podajnikiem - zasobnik (zbiornik) z którego podajnik podaje porcje paliwa do palnika. Kocioł z palnikiem i zasobnikiem są sterowane automatycznie, pracują na podstawie zaprogramowanych parametrów uwzględniających temperaturę zewnętrzną, zadaną temperaturę pomieszczenia oraz zadaną temperaturę wody użytkowej.
	</li>
</ul>



</div>
