<div class="page-header">

	<h1 class="page-title" >Korzysći ze spalania biomasy w piecach Ekopal</h1>
	<a href="<?php echo $this->url(array('controller'=>'index','action'=>'index'));?>">
		<img src="img/main_logo.png" alt="ekopal_logo" class="logo-small" />
	</a>

	
	
</div>
<hr />
<div style="width:80%; padding:50px; margin: auto;">
<h2>Spalanie biomasy w tym urządzeniu to namacalne korzyści</h2>

	<ul class="list">
		<li>oszczędność pieniędzy (tanie paliwo)</li>
		<li>oszczędność czasu</li>
		<li>wygoda użytkowania</li>
		<li>łatwość w utrzymaniu czystości</li>
		<li>niezawodność</li>
		<li>łatwa obsługa</li>
		<li>proste rozpalanie i wygaszanie</li>
		<li>ekologiczne odnawialne paliwo</li>
		<li>mała ilość popiołu (można używać jako nawóz na pole)</li>
		<li>bardzo wysoka sprawność cieplna</li>	
	</ul>	
</div>

