<div id="fb-root"></div>
			<script>
				(function(d, s, id) {
				  var js, fjs = d.getElementsByTagName(s)[0];
				  if (d.getElementById(id)) return;
				  js = d.createElement(s); js.id = id;
				  js.src = "//connect.facebook.net/pl_PL/all.js#xfbml=1";
				  fjs.parentNode.insertBefore(js, fjs);
				}(document, 'script', 'facebook-jssdk'));
			</script>

			<div style="height: 20px;"></div>
<div style="width: 60%; margin:auto;"> 
	<h1>Polub nas na Facebooku!</h1>
	<p>
		Jeżeli interesują Cię nasze piece i chciałbyś regularnie dowiadywać się o tym, co aktualnie robimy, to zapraszamy do polubienia nas na Facebooku. 
	</p>
	<p>
		Zadawaj pytania nam i innym włascicielom pieców naszej produkcji. Z pierwszej ręki dowiedz się jak wygląda ich użytkowanie. 
	</p>
	<p>
		Kliknij przycisk "Lubię to", żeby być z nami w kontakcie.
	</p>
	<div style="height: 20px;"></div>
	<div class="fb-like-box" data-href="https://www.facebook.com/Ekopal2009" data-width="800" data-show-faces="true" data-stream="true" data-header="false"></div>
</div>