<div class="page-header">
	<h1 class="page-title">Skład tarcicy</h1>
	<a href="<?php echo $this->url(array('controller'=>'index','action'=>'index'));?>">
		<img src="img/main_logo.png" alt="ekopal_logo" class="logo-small" />
	</a>	
</div>
<hr />
<div style="width:80%; padding:50px; margin: auto;">
	<div style="float:left; width:60%;">
		<h2>
			Tarcica dębowa sucha o grubości 50mm. klasa I-III.
		</h2>
		<p>
			Posiadamy tarcicę dębową suchą o wilgotności 8-10% grubość ok. 50 mm. długość ok. 4m.
		</p>
		<p>
			Materiał sezonowany ok. 15 miesięcy a następnie suszony.
		</p>
		<p>
			Odpowiedni proces suszenia gwarantuje Państwu materiał odpowiednio odprężony oraz brak pęknięć. Drewno przechowywane w zamkniętym magazynie.
		</p>
		<p>
			Cena dotyczy materiału kl. I-III. Zapraszam do współpracy. 
		</p>
		<p>
			Kontakt telefoniczny: +48 515 266 977
		</p>
		<p>
			mailowy: <a href="mailto:stefan@manka.info">stefan@manka.info</a>
		</p>
		<p>
			<a href="<?php echo $this->url(array('module'=>'default', 'controller'=>'contact-map', 'action'=>'index'));?>">mapa dojazdu</a>
		</p>
	</div>
	<div style="width:40%; float:left; ">
		<p class="crop">
			<a href=""><img src="img/drewno/picture_1.jpg" style="width:100%"/></a>
		</p>
		<p class="crop">
			<a href=""><img src="img/drewno/picture_2.jpg" style="width:100%" /></a>
			
		</p>
		<p class="crop">
			<a href=""><img src="img/drewno/picture_3.jpg"  style="width:100%"/></a>
			
		</p>
		<p class="crop">
			<a href=""><img src="img/drewno/picture_4.jpg" style="width:100%" /></a>
			
		</p>
		
		
		
		
	</div>
</div>