<div class="page-header">

	<h1 class="page-title" >Rozpalanie w piecu</h1>


	<a href="<?php echo $this->url(array('controller'=>'index','action'=>'index'));?>">
		<img src="img/main_logo.png" alt="ekopal_logo" class="logo-small" />
	</a>
	
	
</div>

<hr />
<div class="container">

	<h2>Rozpalanie</h2>
	<p>Rozpalanie paliwa na palniku jest bardzo proste i szybkie a wygaszenie to jedynie wyłączenie załącznika.</p>

	<h2>Obsługa zestawu</h2>
	<p>
		Automatyczny zasobnik po zaprogramowaniu precyzyjnie kontroluje ilość dozowanego paliwa po to by zestaw pracował w sposób ciągły i jednocześnie oszczędny.
	</p>
	<p>
		Obsługa zestawu po rozpaleniu ogranicza się jedynie do dosypywania paliwa do zbiornika oraz do opróżniania komory popielnika z popiołu.
	</p>
	<h2>Bezpieczeństwo</h2>
	<p>
		Brak prądu nie powoduje żadnego zagrożenia dla kotła, ponieważ mała ilość paliwa w palniku bez nadmuchu wentylatora nie podniesie znacząco temperatury kotła. Jeżeli przerwa w dostawie prądu jest kilku godzinna, może wystąpić potrzeba ponownego rozpalenia.
	</p>
	<p>
		W przypadku zagrożenia wycofania się ognia w kierunku zbiornika system sterujący zestawem automatycznie zabezpiecza taki przypadek poprzez tkz.: „strażaka”. Dwa niezależne systemy czuwają nad takim zagrożeniem, które działają podczas pracy urządzenia, jak również w czasie przerw w dostawie prądu.
	</p>
	<h2>Zastosowanie</h2>
	<p>
		Zasobnik z podajnikiem i palnikiem jest rozwiązaniem nowatorskim, nowoczesnym i ekologicznym, który może służyć do ogrzewania domów jednorodzinnych oraz warsztatów produkcyjnych.
	</p>
	<h2>Zaletą tego urządzenia jest:</h2>
	<ul class="list">
		<li>
			spalanie rozdrobnionych odpadów drewnianych, które są tanie oraz ekologiczne.
		</li>
		<li>
			spalanie rozdrobnionej wierzby energetycznej (na jeden dom wystarczy około 20 arów wierzby)
		</li>
		<li>
			znikoma ilość sadzy (czyszczenie kotła raz, góra dwa razy na sezon grzewczy)
		</li>
		<li>
			możliwość utrzymania czystości w kotłowni (drewno nie pyli jak np.: węgiel lub jego pochodne)
		</li>
		<li>
			znikoma ilość popiołu, obsługa bardzo prosta i szybka
		</li>
	</ul>

	<h2>
		Aby urządzenie pracowało niezawodnie, trzeba spełnić tylko dwa warunki:
	</h2>
	
<ul class="list">
	<li>frakcja biomasy nie może być większa niż 7cm x 7cm x 7cm
</li>
<li>drewno powinno mieć nie więcej niż 25% wilgotności</li>
</ul>
</div>	